version: '3'
services:
  db:
    image: postgres:12
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
  app:
    build: .
    volumes:
      - .:/usr/src/app
    environment:
      DB_HOST: db
    ports:
      - '3000:3000'
    depends_on:
      - db
